### ISSUE TITLE
make order example

### ISSUE THREAD

**Issue by Vyllonder** [nlsdfnbch/btfxwss#78]
Hi!

Could you please make an example of how to create an order? Im trying to do it but im not abe¡le to get it. My code is

```
import logging

import time, sys

from btfxwss import BtfxWss

#log = logging.getLogger(__name__)
#
#fh = logging.FileHandler('test.log')
#fh.setLevel(logging.DEBUG)
#sh = logging.StreamHandler(sys.stdout)
#sh.setLevel(logging.DEBUG)
#
#log.addHandler(sh)
#log.addHandler(fh)
#logging.basicConfig(level=logging.DEBUG, handlers=[fh, sh])

wss = BtfxWss(key="xxxxxxx", secret="yyyyy")
wss.start()
time.sleep(5)
wss.authenticate()
time.sleep(3)

order = {
"cid": 12345,
"type": "LIMIT",
"symbol": "tBTCUSD",
"amount": "1.0",
"price": 5500,
"hidden": 0
}


wss.new_order(cid= 12345,
type= "LIMIT",
symbol= "tBTCUSD",
amount= "1.0",
price= 5500,hidden= 0)
wss.stop()
```

Lot of thanks in advance

**Comment by nlsdfnbch** [comment]
Hey @Vyllonder,

in order to figure out what's wrong, I require the logs. Otherwise it's a whole lot of guessing.

simply remove the `#`'s to uncomment the logger and upload the contents of the generated `test.log` (make sure that your api/secret aren't shown). Once you've done that, I'll be sure to help you out asap!

Cheers,

Nils

**Comment by Vyllonder** [comment]
the output is this:
```

INFO:btfxwss.connection:Connection opened

ERROR:btfxwss.queue_processor:Dtype 'auth' does not have a response handler!
INFO:btfxwss.connection:Connection closed
```

Lot of thanks for your fast answer! Im putting silly orders to see if works

**Comment by nlsdfnbch** [comment]
Which version are you currently using? I can see where it crashes in the code, but I cannot see why.
Are you installing via `pip`? if so, are you using the `--pre` flag during installation?

**Comment by nlsdfnbch** [comment]
I just got back from reading #77, and that appears to be a duplicate. Therefore it appears to be an issue in the current pre-release version. Which is odd. 

Could you guys run the code again and set the logging level to `logging.debug` for all handlers ? I need to track the exact path of the message.

**Comment by pchandra-uchicago** [comment]
attached is a log snapshot 
[test.log](https://github.com/nlsdfnbch/btfxwss/files/1434690/test.log)

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago, can you confirm that you have provided an API key when initializing the client? 
According to your logs,  the API key passed via the payload is NULL. That may be our offending source.

**Comment by nlsdfnbch** [comment]
I was able to confirm that this was indeed the problem - I've released a hotfix for both versions on pypi.

Please let me know if this fixes the issue for you!

**Comment by pchandra-uchicago** [comment]
Hi Nils,

Thanks for the quickfix. I am still getting the error below
ERROR:btfxwss.queue_processor:Dtype 'auth' does not have a response handler! (('auth', {'status': 'FAILED', 'code': 10100, 'msg': 'apikey: invalid'}, 1509632140.2461174))
ERROR:btfxwss.queue_processor:Dtype 'auth' does not have a response handler! (('auth', {'status': 'FAILED', 'code': 10100, 'msg': 'apikey: digest invalid'}, 1509632140.2471175))

I cross checked my api_key and it seems fine. Should the key be just a string ("adsad") or should it be a raw string (r"abcd") ? Infact i tried both and it throws the same error

Thanks
Prakash

**Comment by nlsdfnbch** [comment]
Hey @pchandra-uchicago ,
could you check the logs for a message looking like this:
```
DEBUG:btfxwss.connection:send(): Sending payload to API: {"event": "auth", "apiKey": "XXX", "authSig": "2ad2f8e813ec2b1f4bb4e64c", "authPayload": "AUTH1509332245506", "authNonce": "40976"}
```
And post it? It probably says `"apiKey": null` or similar. The fact that it isn't handled by the auth_handler method is curious, tho. Hm.

**Comment by pchandra-uchicago** [comment]
DEBUG:btfxwss.connection:send(): Sending payload to API: {"event": "auth", "apiKey": null, "authSig": "88fbc194f50d3148f5", "authPayload": "AUTH1509634174", "authNonce": "15096341741420024"}

As you said, apiKey is null

**Comment by nlsdfnbch** [comment]
Have you been using the pre-release or the production version?
I saw that, for whatever reason, prod didn't have a fix for the duplicate key issue with `key` and `api_key`, which is fixed now. 
If you were using `master` (the production release on `pypi`), this may have fixed it. Otherwise, we're back to square one.

**Comment by pchandra-uchicago** [comment]
I am using pre-release which you mentioned yesterday (pip install --pre btfxwss). I just downloaded latest version of all files from pypi and replaced the files in my btfxwss folder(folder where btfxwss are placed when i do pip install). Are you facing a similar issue or is it just me messing something up?

**Comment by nlsdfnbch** [comment]
No, no,  I do get the same errors.  I will have a look at this again once I'm home. Its probably something obvious I'm not seeing.

**Comment by pchandra-uchicago** [comment]
Sounds good !  Thanks again. Let me know if you need any assistance testing it.

**Comment by nlsdfnbch** [comment]
Ok, I just tried again and authentication works for me. 

Here's my code:

```python
import time
import logging

from btfxwss import BtfxWss

logging.basicConfig(filename='test.log', filemode='+a', format='%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s')
log = logging.getLogger(__name__)

key = "xs2WF55Nez9L24UaLMmWIXDfqb1MwaDrALVuSuUffbw"
secret = "t2jOZZbmYA4MKetTfrh2cHMChL1rvp3mM0b864CIHGO"

c = BtfxWss(key=key, secret=secret, log_level=logging.DEBUG)
c.start()

while not c.conn.connected.is_set():
    time.sleep(1)

c.authenticate()

while True:
    try:
        time.sleep(1)
    except KeyboardInterrupt:
        c.stop()
```

Feel free to copy and paste this, as is - the account isn't funded and is used for the test backend of `bitex`, my other project. See if you can find a message somewhere along these lines in the log:

```
2017-11-02 20:17:59,666	btfxwss.connection	DEBUG	send(): Sending payload to API: {"apiKey": "xs2WF55Nez9L24UaLMmWIXDfqb1MwaDrALVuSuUffbw", "event": "auth", "authSig": "70674a70f26c64a695100547c5395400a5094ab7638c62065143c67b2b592b589f205a47cbb70e39b499c575cafbf4e0", "authPayload": "AUTH15096502796668342", "authNonce": "15096502796668342"}
2017-11-02 20:17:59,733	btfxwss.connection	DEBUG	_stop_timers(): Timers stopped.
2017-11-02 20:17:59,733	btfxwss.connection	DEBUG	_on_message(): Received new message {"event":"auth","status":"OK","chanId":0,"userId":217076,"auth_id":"68fedca6-51d2-4022-8d58-bd16be550140","caps":{"orders":{"read":1,"write":0},"account":{"read":1,"write":0},"funding":{"read":1,"write":0},"history":{"read":1,"write":0},"wallets":{"read":1,"write":0},"withdraw":{"read":0,"write":0},"positions":{"read":1,"write":0}}} at 1509650279.7338848
2017-11-02 20:17:59,733	btfxwss.connection	DEBUG	_system_handler(): Received a system message: {'chanId': 0, 'status': 'OK', 'userId': 217076, 'auth_id': '68fedca6-51d2-4022-8d58-bd16be550140', 'event': 'auth', 'caps': {'funding': {'write': 0, 'read': 1}, 'history': {'write': 0, 'read': 1}, 'positions': {'write': 0, 'read': 1}, 'account': {'write': 0, 'read': 1}, 'orders': {'write': 0, 'read': 1}, 'wallets': {'write': 0, 'read': 1}, 'withdraw': {'write': 0, 'read': 0}}}
2017-11-02 20:17:59,733	btfxwss.connection	DEBUG	_system_handler(): Distributing {'chanId': 0, 'status': 'OK', 'userId': 217076, 'auth_id': '68fedca6-51d2-4022-8d58-bd16be550140', 'caps': {'funding': {'write': 0, 'read': 1}, 'history': {'write': 0, 'read': 1}, 'positions': {'write': 0, 'read': 1}, 'account': {'write': 0, 'read': 1}, 'orders': {'write': 0, 'read': 1}, 'wallets': {'write': 0, 'read': 1}, 'withdraw': {'write': 0, 'read': 0}}} to _response_handler..
2017-11-02 20:17:59,734	btfxwss.connection	DEBUG	_response_handler(): Passing {'chanId': 0, 'status': 'OK', 'userId': 217076, 'auth_id': '68fedca6-51d2-4022-8d58-bd16be550140', 'caps': {'funding': {'write': 0, 'read': 1}, 'history': {'write': 0, 'read': 1}, 'positions': {'write': 0, 'read': 1}, 'account': {'write': 0, 'read': 1}, 'orders': {'write': 0, 'read': 1}, 'wallets': {'write': 0, 'read': 1}, 'withdraw': {'write': 0, 'read': 0}}} to client..

```

**Comment by pchandra-uchicago** [comment]
I still have the same problem. I am guessing, its issue with the version I am using. Could you please push the changes to release so that I can pip --install.

Thanks
Prakash

**Comment by nlsdfnbch** [comment]
The changes should have been on pypi already. Hm. I have uploaded them again (both production and pre-release should work).

**Comment by nlsdfnbch** [comment]
@Vyllonder , can you confirm this issue persists for you as well ?

**Comment by pchandra-uchicago** [comment]
I just did pip uninstall and then pip install. I ran the code you pasted. 
Have attached the logs below. I see a different error
I am not sure what's going on
[test.log](https://github.com/nlsdfnbch/btfxwss/files/1439305/test.log)

**Comment by nlsdfnbch** [comment]
That's progress! Authentication works - unfortunately the handler that is supposed to process the data for the authenticated channel is missing (or more like is not referenced properly). I will fix this first thing in the morning. 

Thank you for your patience and help!

**Comment by pchandra-uchicago** [comment]
Great ! Thanks again for the quick turnaround

**Comment by eSanity** [comment]
I added 
`print(self.account_channel_names)
 print(data[0])`
to _handle_acccount() since the KeyError comes from
`channel_identifier = self.account_channel_names[data[0]]`
 in the QueueProcessor which returned
`INFO:__main__:Connection opened
INFO:__main__:Connection opened
{'os': 'Orders', 'ps': 'Positions', 'hos': 'Historical Orders', 'hts': 'Trades', 'fls': 'Loans', 'te': 'Trades', 'tu': 'Trades', 'ws': 'Wallets', 'bu': 'Balance Info', 'wu': 'Wallets', 'miu': 'Margin Info', 'fos': 'Offers', 'fiu': 'Funding Info', 'fcs': 'Credits', 'hfos': 'Historical Offers', 'hfcs': 'Historical Credits', 'hfls': 'Historical Loans', 'htfs': 'Funding Trades', 'n': 'Notifications', 'on': 'Order New', 'ou': 'Order Update', 'oc': 'Order Cancel'}
ps
{'os': 'Orders', 'ps': 'Positions', 'hos': 'Historical Orders', 'hts': 'Trades', 'fls': 'Loans', 'te': 'Trades', 'tu': 'Trades', 'ws': 'Wallets', 'bu': 'Balance Info', 'wu': 'Wallets', 'miu': 'Margin Info', 'fos': 'Offers', 'fiu': 'Funding Info', 'fcs': 'Credits', 'hfos': 'Historical Offers', 'hfcs': 'Historical Credits', 'hfls': 'Historical Loans', 'htfs': 'Funding Trades', 'n': 'Notifications', 'on': 'Order New', 'ou': 'Order Update', 'oc': 'Order Cancel'}
ws
{'os': 'Orders', 'ps': 'Positions', 'hos': 'Historical Orders', 'hts': 'Trades', 'fls': 'Loans', 'te': 'Trades', 'tu': 'Trades', 'ws': 'Wallets', 'bu': 'Balance Info', 'wu': 'Wallets', 'miu': 'Margin Info', 'fos': 'Offers', 'fiu': 'Funding Info', 'fcs': 'Credits', 'hfos': 'Historical Offers', 'hfcs': 'Historical Credits', 'hfls': 'Historical Loans', 'htfs': 'Funding Trades', 'n': 'Notifications', 'on': 'Order New', 'ou': 'Order Update', 'oc': 'Order Cancel'}
os
{'os': 'Orders', 'ps': 'Positions', 'hos': 'Historical Orders', 'hts': 'Trades', 'fls': 'Loans', 'te': 'Trades', 'tu': 'Trades', 'ws': 'Wallets', 'bu': 'Balance Info', 'wu': 'Wallets', 'miu': 'Margin Info', 'fos': 'Offers', 'fiu': 'Funding Info', 'fcs': 'Credits', 'hfos': 'Historical Offers', 'hfcs': 'Historical Credits', 'hfls': 'Historical Loans', 'htfs': 'Funding Trades', 'n': 'Notifications', 'on': 'Order New', 'ou': 'Order Update', 'oc': 'Order Cancel'}
fos
{'os': 'Orders', 'ps': 'Positions', 'hos': 'Historical Orders', 'hts': 'Trades', 'fls': 'Loans', 'te': 'Trades', 'tu': 'Trades', 'ws': 'Wallets', 'bu': 'Balance Info', 'wu': 'Wallets', 'miu': 'Margin Info', 'fos': 'Offers', 'fiu': 'Funding Info', 'fcs': 'Credits', 'hfos': 'Historical Offers', 'hfcs': 'Historical Credits', 'hfls': 'Historical Loans', 'htfs': 'Funding Trades', 'n': 'Notifications', 'on': 'Order New', 'ou': 'Order Update', 'oc': 'Order Cancel'}
fcs
{'os': 'Orders', 'ps': 'Positions', 'hos': 'Historical Orders', 'hts': 'Trades', 'fls': 'Loans', 'te': 'Trades', 'tu': 'Trades', 'ws': 'Wallets', 'bu': 'Balance Info', 'wu': 'Wallets', 'miu': 'Margin Info', 'fos': 'Offers', 'fiu': 'Funding Info', 'fcs': 'Credits', 'hfos': 'Historical Offers', 'hfcs': 'Historical Credits', 'hfls': 'Historical Loans', 'htfs': 'Funding Trades', 'n': 'Notifications', 'on': 'Order New', 'ou': 'Order Update', 'oc': 'Order Cancel'}
fls
{'os': 'Orders', 'ps': 'Positions', 'hos': 'Historical Orders', 'hts': 'Trades', 'fls': 'Loans', 'te': 'Trades', 'tu': 'Trades', 'ws': 'Wallets', 'bu': 'Balance Info', 'wu': 'Wallets', 'miu': 'Margin Info', 'fos': 'Offers', 'fiu': 'Funding Info', 'fcs': 'Credits', 'hfos': 'Historical Offers', 'hfcs': 'Historical Credits', 'hfls': 'Historical Loans', 'htfs': 'Funding Trades', 'n': 'Notifications', 'on': 'Order New', 'ou': 'Order Update', 'oc': 'Order Cancel'}
ats
ERROR:__main__:Channel ID does not have a data handler! ('data', [0, 'ats', []], 1509659136.648898)
ERROR:__main__:Channel ID does not have a data handler! ('data', [0, 'ats', []], 1509659136.648898)`

As you already said the channel is missing, however in the Bitfinex API documentation I cannot find any mention of the 'ats' channel. What does 'ats' even mean? I cannot find any mention of 'ats' in older btfxwss code either, which means Bitfinex must have changed something. 

Simply ignoring the error seems to work. The ats message for the rest is empty, which is weird. I hope this information might help you tomorrow morning

**Comment by nlsdfnbch** [comment]
@eSanity , excellent catch! I thought it occurred further upstream. I have contacted Bitfinex Support, in the hope that they can shed some light on this issue.

**Comment by nlsdfnbch** [comment]
For test purposes I have added a dummy name for the 'ats' message type. See if this resolves the issue?

**Comment by eSanity** [comment]
@nlsdfnbch In btfxwss-1.2.0b4 authentication broke again. The commit that solved #76 and #61 was not included. Re-adding the line `payload = json.dumps(payload)` to the release branch in connection.py at line 268 should fix the issue. 

I am not (at all) familiar with GitHub, is there an easier way for you that I can send you these changes and you only have to press a button? Thanks for developing this project, by the way.

**Comment by pchandra-uchicago** [comment]
Nils,
Have you pushed the 'ats' fix to production

**Comment by eSanity** [comment]
@pchandra-uchicago 
The 'ats' fix is currently in the release branch but I would advice _not upgrading_ since the issue  (#79)  I highlighted before your comment will stop your program from working whereas you can safely ignore any 'ats' errors for now.
The line that fixes the 'ats' problem can be seen below
https://github.com/nlsdfnbch/btfxwss/blob/01c17c689e7bfb3f65c42f80f4c39e781001248a/btfxwss/queue_processor.py#L89

**Comment by nlsdfnbch** [comment]
@eSanity, holy shit muffin, batman! How did that happen D:< It's fixed now!

@pchandra-uchicago , the `--pre` version now has this fix

Once this is confirmed to be working as expected, I'll push it to production, too.

**Comment by eSanity** [comment]
@nlsdfnbch Just installed 0b5, listened to .orders_update and submitted an order via Bitfinex website. Can confirm it works now. 

(Slightly off-topic but looking at the new orders method in the API, why do you not have to supply a wallet type to execute the order from? Does it default to the exchange wallet? I already asked Bitfinex Support but they are _very slow_ with a response)

**Comment by nlsdfnbch** [comment]
@eSanity, wohoo!

If you look at the [documentation](https://bitfinex.readme.io/v2/reference#ws-input-order-new), it states that you must supply a `symbol` when submitting an order - depending on what you want to trade, it uses that wallet as required.

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago , fix no in `production` - could you confirm this?

**Comment by pchandra-uchicago** [comment]
Hey Nils,

I still have the same issue when I run my code. When i run your code it seems to work fine. I have attached the logs for your code and my code. My code is below. 

`try:
    wss = BtfxWss(key="abcdef", secret="defghd",   log_level=logging.DEBUG)                                                            
    wss.start()

    while not wss.conn.connected.is_set():
        time.sleep(1)

    wss.authenticate()    
except Exception as e:
    print(e)`

I took the latest update from production. Did a pip uninstall and then pip install. Really weird !
[test_mycode.log](https://github.com/nlsdfnbch/btfxwss/files/1441708/test_mycode.log)
[test_yourcode.log](https://github.com/nlsdfnbch/btfxwss/files/1441709/test_yourcode.log)

**Comment by eSanity** [comment]
@pchandra-uchicago You are not sending a valid API key. 
@nlsdfnbch's API payload
`2017-11-03 11:05:09,665	btfxwss.connection	DEBUG	send(): Sending payload to API: {"event": "auth", "apiKey": "xs2WF55Nez9L24UaLMmWIXDfqb1MwaDrALVuSuUffbw", "authSig": "72b1d3eb7b5774a5ab960af0a5af9a3a9a57a74572613602ffa6b1190f987f857b693cc7e4e83d7228a17abb5d1f5eb7", "authPayload": "AUTH15097251096652732", "authNonce": "15097251096652732"}`
@pchandra-uchicago's  API payload
`DEBUG:btfxwss.connection:send(): Sending payload to API: {"event": "auth", "apiKey": "abcdefgh", "authSig": "d6f52c175617d9fsdbsjkafdkaslfdsfjasdfikkaa", "authPayload": "AUTH15097249510052642", "authNonce": "15097249510052642"}`

**Comment by pchandra-uchicago** [comment]
I changed that in the logs.. I will cross check again. But why do you say so ?

**Comment by nlsdfnbch** [comment]
@eSanity , @pchandra-uchicago almost - somehow, the digest wasn't valid

```
DEBUG:btfxwss.connection:_on_message(): Received new message {"event":"auth","status":"FAILED","chanId":0,"code":10100,"msg":"apikey: digest invalid"} at 1509724951.2112849```

**Comment by eSanity** [comment]
@nlsdfnbch @pchandra-uchicago what prompted my question regarding the key/secret was indeed the failed digest message, the size difference between your "authSig" and his "authSig" and the error code '10100' for failed authentication. 

Have you tried with another key/secret yet?

**Comment by pchandra-uchicago** [comment]
I did change all those fields ( authSig, websocket key,  cookie etc)..anything that is like a key, i have modified

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago, OK, but still there seems to be something off - just to make sure it isn't the key/secret, could you generate a new pair and try again? Because this is the only variable that differs, as far as I understand.

**Comment by pchandra-uchicago** [comment]
@nlsdfnbch , I will try by generating a new key and secret. Will keep you guys posted

Thanks

**Comment by pchandra-uchicago** [comment]
Hi Nils,

Just tried with new key and secret. I have attached the logs below. It throws error the first time and looking at logs, it seems like its authenticating in subsequent pings. 
[test_1106.log](https://github.com/nlsdfnbch/btfxwss/files/1446614/test_1106.log)

**Comment by pchandra-uchicago** [comment]
@nlsdfnbch @eSanity ,

I had issues with API access for my account. Got that fixed and now it seems to work fine.
Thanks for your patience guys.

@eSanity  - did you get the new order thing working ?

Cheers

**Comment by nlsdfnbch** [comment]
Is it not working for you? @pchandra-uchicago

**Comment by pchandra-uchicago** [comment]
Nils,

Authentication works. Thanks for the help.
However, I have issues resetting order book . Could you please take a look?

Thanks

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago, I'm on it. I'll close this, since the issue is resolved.

**Comment by pchandra-uchicago** [comment]
Thanks Nils. Let me know if you need any assistance with it.
